### ISSUE TITLE
Using tiles in MBTiles tileset format?

### ISSUE THREAD

**Issue by rybesh** [substack/mixmap-tiles#1]
I don't understand how to generate a layers.json for mixmap-tiles. The downloadable tiles that I am familiar with (for example [OSM](https://openmaptiles.com/downloads/planet/)) are usually provided in the [MBTiles](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md) format, which names tiles as numbered columns and rows within zoom levels, but layers.json uses bboxes in degrees latitude and longitude. Given a directory tree full of MBTiles-style tiles, e.g.:
```
├── 0
│   └── 0
│       └── 0.png
├── 1
│   ├── 0
│   │   ├── 0.png
│   │   └── 1.png
│   └── 1
│       ├── 0.png
│       └── 1.png
etc.
```
… how do I generate layers.json so that I can use them with mixmap-tiles?

**Comment by substack** [comment]
Here's some code that converts slippy map coordinates to bboxes in java: https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Tile_bounding_box

Here's a function in javascript that ought to do the trick:

``` js
var PI = Math.PI
function slippyBBox (x, y, z) {
  var p2z = Math.pow(2.0,z)
  return [
     x / p2z * 360.0 - 180, // west
     Math.atan(Math.sinh(PI-(2.0*PI*(y+1))/p2z))/PI*180.0, // south
     (x+1) / p2z * 360.0 - 180, // east
     Math.atan(Math.sinh(PI-(2.0*PI*y)/p2z))/PI*180.0 // north
  ]
}
```

**Comment by substack** [comment]
One more complication is that mbtiles have their own `bounds` extents in the metadata so these equations need to be projected into those boundaries.

**Comment by substack** [comment]
Reading more, mbtiles uses a subset of http://wiki.osgeo.org/wiki/Tile_Map_Service_Specification
Reading this, I'm not entirely sure if the coordinates are projected onto the bounding box or if the bounds are for informational purposes. You may need to swap y and x with mbtiles compared to slippy tiles.

**Comment by rybesh** [comment]
Thanks, this is very helpful!
